
(function(){
  'use strict';
  var root=document.getElementById('despegaDashboardApp');
  var dashboardView=document.getElementById('dashboardView');
  if(!root||!dashboardView)return;
  var state={view:localStorage.getItem('despegaDashboardView')||'home',category:'all',search:'',saved:readJSON('despegaSavedOpportunities',[]),viewed:readJSON('despegaViewedOpportunities',[]),routeSkillsStarted:localStorage.getItem('despegaRouteSkillsStarted')==='true',novaOpen:false};
  var catalog=[
    {id:'mtpe-capacitate',type:'curso',title:'Capacítate y certifícate en Empleos Perú',provider:'Ministerio de Trabajo y Promoción del Empleo',modality:'En línea',duration:'A tu ritmo',cost:'Gratuito',level:'Abierto',description:'Capacitación online gratuita para fortalecer tu empleabilidad y acceder a certificación según las condiciones de cada curso.',requirements:['Tener una cuenta en Empleos Perú'],tags:['empleo','habilidades','digital','certificación','tecnología'],source:{name:'Gob.pe / MTPE',url:'https://www.gob.pe/23794-obtener-capacitacion-y-certificacion-en-empleos-peru'},application:{url:'https://www.empleosperu.gob.pe/portal-mtpe/#/',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'pronabec-concursos',type:'beca',title:'Concursos de becas y créditos PRONABEC',provider:'PRONABEC',modality:'En línea',duration:'Convocatorias variables',cost:'Gratuito',level:'Secundaria / Superior',description:'Portal oficial para revisar concursos de becas y créditos, su vigencia, requisitos y bases antes de postular.',requirements:['Revisar los requisitos de cada convocatoria'],tags:['beca','educación','estudios','apoyo','universidad','instituto'],source:{name:'PRONABEC',url:'https://www.pronabec.gob.pe/concursos-becas-creditos/'},application:{url:'https://www.pronabec.gob.pe/concursos-becas-creditos/',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'conecta-empleo-digital',type:'curso',title:'Formación digital Conecta Empleo',provider:'Fundación Telefónica',modality:'En línea',duration:'Según curso',cost:'Gratuito',level:'Abierto',description:'Formación online gratuita orientada a competencias digitales y empleabilidad.',requirements:[],tags:['tecnología','digital','programación','empleo','habilidades'],source:{name:'Fundación Telefónica',url:'https://www.fundaciontelefonica.com/noticias/cursos-gratuitos-ciberseguridad/'},application:{url:'https://www.fundaciontelefonica.com/noticias/cursos-gratuitos-ciberseguridad/',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'google-skillshop',type:'curso',title:'Google Skillshop',provider:'Google',modality:'En línea',duration:'A tu ritmo',cost:'Consultar en la plataforma',level:'Abierto',description:'Formación online oficial sobre herramientas de Google, con rutas de aprendizaje y certificaciones según el producto.',requirements:[],tags:['tecnología','digital','marketing','analytics','google'],source:{name:'Google Skillshop',url:'https://skillshop.withgoogle.com/'},application:{url:'https://skillshop.withgoogle.com/',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'cisco-python-essentials-1',type:'curso',title:'Python Essentials 1',provider:'Cisco Networking Academy',modality:'En línea',duration:'30 horas',cost:'Consultar en la plataforma',level:'Principiante',description:'Curso introductorio oficial para aprender conceptos fundamentales de programación y desarrollar habilidades iniciales con Python.',requirements:[],tags:['tecnología','programación','python','digital','habilidades'],source:{name:'Cisco Networking Academy',url:'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html'},application:{url:'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'senati-escuela-superior',type:'curso',title:'Carreras de alta tecnología - Escuela Superior SENATI',provider:'SENATI',modality:'Semipresencial',duration:'8 semestres',cost:'Consultar en la institución',level:'Educación superior',description:'Portal oficial de la Escuela de Educación Superior Tecnológica de SENATI para explorar carreras de alta tecnología e ingeniería.',requirements:['Consultar requisitos de admisión vigentes en SENATI'],tags:['tecnología','ingeniería','mecatrónica','sistemas','datos','educación'],source:{name:'Escuela Superior SENATI',url:'https://escuelasuperior.senati.edu.pe/'},application:{url:'https://escuelasuperior.senati.edu.pe/',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'tecsup-educacion-continua',type:'curso',title:'Catálogo de Educación Continua TECSUP',provider:'TECSUP',modality:'Presencial / Semipresencial',duration:'Según programa',cost:'Variable',level:'Abierto según programa',description:'Catálogo oficial de cursos cortos, programas integrales y especializaciones de educación continua de TECSUP.',requirements:['Consultar los requisitos y condiciones de cada programa'],tags:['tecnología','mecánica','mecatrónica','digital','habilidades','educación'],source:{name:'TECSUP',url:'https://www.tecsup.edu.pe/buscador-y-biblioteca/'},application:{url:'https://www.tecsup.edu.pe/buscador-y-biblioteca/',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'empleos-peru-bolsa',type:'empleo',title:'Bolsa de Trabajo de Empleos Perú',provider:'Ministerio de Trabajo y Promoción del Empleo',modality:'En línea',duration:'Permanente',cost:'Gratuito',level:'Mayores de edad',description:'Portal público para registrar el perfil laboral y revisar vacantes publicadas en la Bolsa de Trabajo.',requirements:['Ser mayor de edad','Contar con documento de identidad y estar habilitado legalmente para trabajar'],tags:['empleo','trabajo','vacantes','experiencia'],source:{name:'MTPE / Empleos Perú',url:'https://www.empleosperu.gob.pe/portal-mtpe/#/'},application:{url:'https://www.empleosperu.gob.pe/portal-mtpe/#/login',deadline:null},verification:{status:'verified',verified_at:'2026-09-26',source_type:'official'}},
    {id:'pronabec-beca18-2026',type:'beca',title:'Beca 18 - Convocatoria 2026',provider:'PRONABEC',modality:'En línea',duration:'Convocatoria 2026',cost:'Gratuito',level:'Secundaria',description:'Convocatoria integral de PRONABEC cuya etapa de postulación 2026 ya finalizó.',requirements:['Consultar bases oficiales'],tags:['beca','educación','estudios'],source:{name:'PRONABEC',url:'https://www.pronabec.gob.pe/beca-18/'},application:{url:'https://www.pronabec.gob.pe/beca-18/',deadline:'2026-08-09'},verification:{status:'expired',verified_at:'2026-09-26',source_type:'official'}}
  ];
  function readJSON(key,fallback){try{var value=JSON.parse(localStorage.getItem(key)||'');return value==null?fallback:value;}catch(_){return fallback;}}
  function saveJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch(_){}}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function itemText(item){if(typeof item==='string')return item.trim();if(!item||typeof item!=='object')return '';return String(item.value||item.description||item.name||item.category||item.subcategory||'').trim();}
  function list(profile,key){var rows=Array.isArray(profile&&profile[key])?profile[key]:[];var seen={};return rows.map(itemText).filter(function(value){var k=value.toLowerCase();if(!value||seen[k])return false;seen[k]=true;return true;});}
  function titleCase(value){return String(value||'').replace(/[_-]+/g,' ').replace(/\b\w/g,function(x){return x.toUpperCase();});}
  function isVerifiedOpportunity(opp){return Boolean(opp&&opp.verification&&opp.verification.status==='verified');}
  function activeCatalog(){return catalog.filter(isVerifiedOpportunity);}
  function getVerifiedUrl(id){var o=catalog.find(function(row){return row.id===id;});if(!isVerifiedOpportunity(o))return'';return String((o.application&&o.application.url)||(o.source&&o.source.url)||'').trim();}
  function matchReasons(opp,m){var reasons=[],hay=(m.interests.concat(m.skills,m.goals)).join(' ').toLowerCase();(opp.tags||[]).forEach(function(tag){if(hay.indexOf(String(tag).toLowerCase())>=0&&reasons.length<3)reasons.push('Coincide con '+tag);});var barrierText=(m.barriers||[]).join(' ').toLowerCase();if(opp.cost==='Gratuito'&&/(dinero|econ[oó]mic|costo|pagar|pago)/i.test(barrierText))reasons.push('Es una opción gratuita frente a la barrera económica registrada');if(!reasons.length)reasons.push('Está disponible en el catálogo verificado de DESPEGA');return reasons.slice(0,3);}
  function buildRouteModel(m){var steps=[{id:'profile',n:1,title:'Conoce tu punto de partida',desc:'Tus datos, situación e información de Nova forman el inicio de la ruta.',status:m.completedOnboarding?'done':'current',label:m.completedOnboarding?'Completado':'En curso'},{id:'skills',n:2,title:'Fortalece habilidades',desc:'Explora formación relacionada con habilidades e intereses que quieras desarrollar.',status:state.routeSkillsStarted?'current':'pending',label:state.routeSkillsStarted?'En curso':'Pendiente'},{id:'opportunities',n:3,title:'Explora oportunidades',desc:'Compara opciones verificadas, sus requisitos y fuentes oficiales.',status:m.viewedCount>0?'current':'pending',label:m.viewedCount>0?'En curso':'Pendiente'},{id:'action',n:4,title:'Da tu siguiente paso',desc:'Guarda una opción, revisa su fuente oficial y decide si quieres continuar.',status:m.savedCount>0?'current':'pending',label:m.savedCount>0?'En curso':'Pendiente'}];var current=steps.find(function(s){return s.status==='current';})||steps[steps.length-1],next=steps.find(function(s){return s.status==='pending';})||current;return{progress:m.routeProgress,current_step:current.id,next_step:next.id,completed_steps:steps.filter(function(s){return s.status==='done';}).map(function(s){return s.id;}),pending_steps:steps.filter(function(s){return s.status==='pending';}).map(function(s){return s.id;}),steps:steps};}
  function educationLabel(raw){var value=String(raw||'').trim();var map={none:'Sin estudios formales registrados',primary:'Primaria',secondary:'Secundaria',technical:'Educación técnica',higher:'Educación superior',Ninguno:'Sin estudios formales registrados',Primaria:'Primaria',Secundaria:'Secundaria',Superior:'Educación superior'};return map[value]||value||'Nivel educativo por completar';}
  function yesNoLabel(raw){var value=String(raw||'').toLowerCase();if(['yes','si','sí','true'].indexOf(value)>=0)return'Sí';if(['no','false'].indexOf(value)>=0)return'No';return raw||'Por completar';}
  function getModel(){
    var snapshot=readJSON('despegaOnboardingSnapshot',{}),step1=snapshot.step1||readJSON('despegaRegisterStep1',{}),step2=snapshot.step2||readJSON('despegaRegisterStep2',{}),profile=(snapshot.step3&&snapshot.step3.profile)||readJSON('despegaAIProfile',{}),history=(snapshot.step3&&snapshot.step3.conversationHistory)||readJSON('despegaConversationHistory',[]),status=(snapshot.step3&&snapshot.step3.dimensionStatus)||readJSON('despegaDimensionStatus',{});
    var useful=Number((snapshot.step3&&snapshot.step3.usefulAnswersCount)||(snapshot.step3&&snapshot.step3.answersCount)||0),firstName=String(step1.firstName||'').trim().split(/\s+/)[0]||'bienvenido',fullName=[step1.firstName,step1.lastName].filter(Boolean).join(' ').trim()||'Tu cuenta';
    var goals=list(profile,'goals'),interests=list(profile,'interests'),skills=list(profile,'skills'),experience=list(profile,'experience'),barriers=list(profile,'barriers'),training=list(profile,'training_needs');
    var completedOnboarding=localStorage.getItem('despegaOnboardingCompleted')==='true'||Boolean(snapshot.completedAt),savedCount=Array.isArray(state.saved)?state.saved.length:0,viewedCount=Array.isArray(state.viewed)?state.viewed.length:0;
    var routeSteps=[completedOnboarding?'done':'current',state.routeSkillsStarted?'current':'pending',viewedCount>0?'current':'pending','pending'],completedRoute=routeSteps.filter(function(x){return x==='done';}).length,routeProgress=Math.round((completedRoute/routeSteps.length)*100);
    return{snapshot:snapshot,step1:step1,step2:step2,profile:profile,history:history,status:status,firstName:firstName,fullName:fullName,location:[step1.district,step1.province,step1.department].filter(Boolean).join(', '),education:educationLabel(step2.educationLevel||(profile.education&&profile.education.level)),studying:yesNoLabel(step2.studyingNow||(profile.education&&profile.education.currentlyStudying)),working:yesNoLabel(step2.workingNow||(profile.employment&&profile.employment.currentlyWorking)),goals:goals,interests:interests,skills:skills,experience:experience,barriers:barriers,training:training,usefulAnswers:useful,savedCount:savedCount,viewedCount:viewedCount,routeSteps:routeSteps,routeProgress:routeProgress,completedOnboarding:completedOnboarding};
  }
  function icon(name){
    var paths={
      home:'<path d="M3 10.5 12 3l9 7.5v8.25A2.25 2.25 0 0 1 18.75 21h-4.5v-6h-4.5v6h-4.5A2.25 2.25 0 0 1 3 18.75z"/>',
      route:'<path d="M5 4.5h11.5a2.5 2.5 0 0 1 0 5H8a2.5 2.5 0 0 0 0 5h8a2.5 2.5 0 0 1 0 5H5"/><circle cx="5" cy="4.5" r="1.5"/><circle cx="5" cy="19.5" r="1.5"/>',
      opportunities:'<rect x="4" y="5" width="16" height="14" rx="3"/><path d="M8 9h8M8 13h5"/>',
      progress:'<path d="M5 19V9M10 19V5M15 19v-7M20 19V3"/>',
      profile:'<circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/>'
    };
    return '<svg class="dd-icon-svg" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+(paths[name]||'<circle cx="12" cy="12" r="4"/>')+'</svg>';
  }
  function navButton(view,label){return'<button class="dd-nav-btn" type="button" data-dd-nav="'+esc(view)+'"'+(state.view===view?' aria-current="page"':'')+'><span class="dd-nav-icon" aria-hidden="true">'+icon(view)+'</span><span>'+esc(label)+'</span></button>';}
  function shell(){
    var m=getModel();
    root.innerHTML=['<div class="dd-app"><aside class="dd-sidebar" aria-label="Navegación del dashboard"><div class="dd-brand">DESPEGA</div><nav class="dd-nav">',navButton('home','Inicio'),navButton('route','Mi Ruta'),navButton('opportunities','Oportunidades'),navButton('progress','Progreso'),navButton('profile','Perfil'),'</nav><div class="dd-sidebar-footer">Tu información se mantiene separada del catálogo. Puedes revisar y actualizar tu perfil cuando quieras.</div></aside><section class="dd-main"><header class="dd-topbar"><button class="dd-top-icon" type="button" aria-label="Notificaciones">♧</button><button class="dd-lang" type="button" aria-label="Idioma">ES⌄</button><button class="dd-account" type="button" data-dd-nav="profile" aria-label="Abrir perfil"><span class="dd-account-avatar">'+esc((m.firstName[0]||'U').toUpperCase())+'</span><span class="dd-account-name">'+esc(m.fullName)+'</span><span>⌄</span></button></header><div class="dd-content"><section class="dd-page" data-dd-page="home"></section><section class="dd-page" data-dd-page="route"></section><section class="dd-page" data-dd-page="opportunities"></section><section class="dd-page" data-dd-page="progress"></section><section class="dd-page" data-dd-page="profile"></section></div></section></div><button class="dd-nova-launcher nova-fab is-idle" id="ddNovaLauncher" type="button" aria-label="Abrir chat con Nova"><span class="nova-avatar" aria-hidden="true"><span class="nova-eyes"><i></i><i></i></span><span class="nova-mouth"></span></span><span class="nova-status-ring" aria-hidden="true"></span><span class="nova-fab-tooltip">Habla con Nova</span></button><aside class="dd-nova-panel" id="ddNovaPanel" aria-label="Nova"><div class="dd-nova-head"><strong>Nova</strong><button class="dd-nova-close" type="button" aria-label="Cerrar">×</button></div><div class="dd-nova-body"><p id="ddNovaMessage"></p><div class="dd-nova-actions"><button type="button" data-dd-nova-go="profile">Revisar lo que entendimos de tu perfil</button><button type="button" data-dd-nova-go="route">Ver tu ruta y próximos pasos</button><button type="button" data-dd-nova-go="opportunities">Explorar opciones y compararlas</button></div></div></aside><div class="dd-modal" id="ddModal" role="dialog" aria-modal="true" aria-label="Detalle de oportunidad"><div class="dd-modal-card" id="ddModalCard"></div></div><div class="dd-toast" id="ddToast" role="status" aria-live="polite"></div>'].join('');
    bindShell();renderAll();
  }
  function pageHead(eyebrow,title,subtitle,extra){return'<div class="dd-page-head dd-motion-head"><div><span class="dd-eyebrow">'+esc(eyebrow)+'</span><h1 class="dd-page-title">'+esc(title)+' <span class="dd-spark">✦</span></h1><p class="dd-page-subtitle">'+esc(subtitle)+'</p></div>'+(extra||'')+'</div>';}
  function sectionHead(title,sub,button){return'<div class="dd-card-head"><div><h2 class="dd-section-title">'+esc(title)+'</h2>'+(sub?'<p class="dd-section-sub">'+esc(sub)+'</p>':'')+'</div>'+(button||'')+'</div>';}
  function tagRows(values,limit){var rows=(values||[]).slice(0,limit||6);if(!rows.length)return'<span class="dd-tag">Aún no registrado</span>';return rows.map(function(v){return'<span class="dd-tag">'+esc(v)+'</span>';}).join('');}
  function matchScore(opp,m){var hay=(m.interests.concat(m.skills,m.goals)).join(' ').toLowerCase();return opp.tags.reduce(function(score,tag){return score+(hay.indexOf(tag.toLowerCase())>=0?1:0);},0);}
  function sortedCatalog(m){return activeCatalog().slice().sort(function(a,b){var d=matchScore(b,m)-matchScore(a,m);return d||a.title.localeCompare(b.title,'es');});}
  function ring(p,label){return'<div class="dd-ring" data-progress="'+Number(p||0)+'" style="--p:0"><span><b data-ring-value>0%</b><small>'+esc(label||'')+'</small></span></div>';}
  function miniOpp(o){return'<article class="dd-mini-opp"><div class="dd-mini-img"><span class="dd-type">'+esc(titleCase(o.type))+'</span></div><div class="dd-mini-body"><h4>'+esc(o.title)+'</h4><div class="dd-mini-meta"><span>▣ '+esc(o.provider)+'</span><span>⌂ '+esc(o.modality)+'</span><span>◷ '+esc(o.duration)+'</span></div></div></article>';}
  function buildRecentActivity(m){var rows=[];if(m.completedOnboarding)rows.push(['◫','Completaste tu perfil','Tus respuestas quedaron organizadas para la ruta.','Ahora']);if(m.viewedCount)rows.push(['⌕','Exploraste oportunidades',m.viewedCount+' opción(es) revisadas.','Esta sesión']);if(m.savedCount)rows.push(['♡','Guardaste oportunidades',m.savedCount+' opción(es) para revisar después.','Esta sesión']);if(state.routeSkillsStarted)rows.push(['✓','Iniciaste una etapa de ruta','Fortalecer habilidades quedó en curso.','Esta sesión']);if(!rows.length)rows.push(['•','Sin actividad reciente','Tus acciones aparecerán aquí.','']);return rows.slice(0,4).map(function(r){return'<div class="dd-activity-row"><span class="dd-activity-icon">'+r[0]+'</span><div><strong>'+esc(r[1])+'</strong><span>'+esc(r[2])+'</span></div><time>'+esc(r[3])+'</time></div>';}).join('');}
  function profileCompleteness(m){
    var fields=[m.education&&m.education.indexOf('por completar')<0,m.location,m.goals.length,m.interests.length,m.skills.length];
    var done=fields.filter(Boolean).length;
    return {percent:Math.round((done/fields.length)*100),missing:fields.length-done};
  }
  function youthIllustration(){
    return '<div class="dd-youth-scene" aria-hidden="true"><svg class="dd-youth-svg" viewBox="0 0 260 220"><defs><linearGradient id="ddBody" x1="0" x2="1"><stop stop-color="#8D6CF4"/><stop offset="1" stop-color="#5C3CC5"/></linearGradient></defs><circle cx="130" cy="82" r="40" fill="#F1B99E"/><path d="M92 79c2-39 75-49 79 4-10-15-25-23-39-22-16 0-28 7-40 18Z" fill="#2E2253"/><path d="M67 215c5-67 33-101 63-101s58 34 63 101Z" fill="url(#ddBody)"/><circle cx="197" cy="57" r="20" fill="#52D6DD" opacity=".9"/><circle cx="52" cy="56" r="15" fill="#FFBF1F" opacity=".95"/></svg><span class="dd-orbit dd-orbit-a">⌘</span><span class="dd-orbit dd-orbit-b">✦</span><span class="dd-orbit dd-orbit-c">↗</span></div>';
  }
  function opportunityIllustration(type){
    var icon=type==='beca'?'★':type==='empleo'?'↗':type==='evento'?'✦':type==='voluntariado'?'♡':'</>';
    return '<div class="dd-opp-art dd-opp-art-'+esc(type)+'" aria-hidden="true"><span>'+esc(icon)+'</span><i></i><b></b></div>';
  }
  function routeMap(route){
    var steps=route.steps||[], positions=[[45,112],[190,58],[338,118],[488,66]];
    var nodes=steps.map(function(s,i){var p=positions[i];return'<g class="dd-route-map-node '+(s.status==='done'?'is-done':s.status==='current'?'is-current':'is-pending')+'" transform="translate('+p[0]+' '+p[1]+')"><circle r="18"/><text text-anchor="middle" dominant-baseline="middle">'+s.n+'</text><foreignObject x="-62" y="28" width="124" height="42"><div xmlns="http://www.w3.org/1999/xhtml" class="dd-route-map-label">'+esc(s.title)+'</div></foreignObject></g>';}).join('');
    return '<div class="dd-route-map-wrap"><svg class="dd-route-map" viewBox="0 0 540 180" role="img" aria-label="Mapa de tu ruta"><path class="dd-route-path-bg" d="M45 112 C115 112 116 58 190 58 S266 118 338 118 S412 66 488 66"/><path class="dd-route-path-progress" data-route-progress="'+Number(route.progress||0)+'" d="M45 112 C115 112 116 58 190 58 S266 118 338 118 S412 66 488 66"/>'+nodes+'</svg></div>';
  }
  function timelineRow(done,title,sub){return'<div class="dd-timeline-item '+(done?'is-done':'')+'"><span class="dd-timeline-dot">'+(done?'✓':'')+'</span><div><strong>'+esc(title)+'</strong><p>'+esc(sub||'')+'</p></div></div>';}
  function animateNumber(node,target,duration){
    if(!node||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
    var start=performance.now(),from=0,to=Number(target||0);
    function frame(now){var p=Math.min(1,(now-start)/(duration||700)),e=1-Math.pow(1-p,3);node.textContent=Math.round(from+(to-from)*e);if(p<1)requestAnimationFrame(frame);}
    requestAnimationFrame(frame);
  }
  function animateRing(node,target){
    if(!node)return;var to=Number(target||0);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){node.style.setProperty('--p',to);return;}
    var start=performance.now();function frame(now){var p=Math.min(1,(now-start)/900),v=Math.round(to*(1-Math.pow(1-p,3)));node.style.setProperty('--p',v);var label=node.querySelector('[data-ring-value]');if(label)label.textContent=v+'%';if(p<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);
  }
  function animateRoutePath(scope){
    var path=scope&&scope.querySelector('.dd-route-path-progress');if(!path)return;var length=path.getTotalLength();var pct=Math.max(0,Math.min(100,Number(path.getAttribute('data-route-progress')||0)));path.style.strokeDasharray=String(length);path.style.strokeDashoffset=String(length);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){path.style.strokeDashoffset=String(length*(1-pct/100));return;}path.animate([{strokeDashoffset:length},{strokeDashoffset:length*(1-pct/100)}],{duration:900,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'});
  }
  function staggerElements(scope){
    if(!scope||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
    Array.prototype.forEach.call(scope.querySelectorAll('.dd-motion-card'),function(node,i){node.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:320,delay:Math.min(i,3)*45,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'});});
  }
  function initDashboardMotion(){
    var page=document.querySelector('.dd-page.is-active');if(!page)return;
    requestAnimationFrame(function(){
      staggerElements(page);
      Array.prototype.forEach.call(page.querySelectorAll('.dd-ring,.dd-big-ring'),function(r){animateRing(r,Number(r.getAttribute('data-progress')||0));});
      Array.prototype.forEach.call(page.querySelectorAll('[data-count]'),function(n){animateNumber(n,Number(n.getAttribute('data-count')||0),650);});
      animateRoutePath(page);
    });
  }
  function renderHome(){var m=getModel(),opps=sortedCatalog(m).slice(0,3),p=document.querySelector('[data-dd-page="home"]');if(!p)return;var quick=[{icon:'profile',value:m.completedOnboarding?'✓':'—',label:'Onboarding'},{icon:'progress',value:String(m.usefulAnswers),label:'Respuestas'},{icon:'opportunities',value:String(m.savedCount),label:'Guardadas'},{icon:'route',value:String(m.routeProgress),label:'Ruta',percent:true}];var interests=m.interests.slice(0,3);p.innerHTML=[pageHead('TU ESPACIO','Hola, '+m.firstName,'Tu ruta comienza aquí. Revisa tu siguiente paso y explora opciones a tu ritmo.','<span class="dd-profile-ready">'+(m.completedOnboarding?'Onboarding completado':'Punto de partida pendiente')+'</span>'),'<div class="dd-home-grid"><div class="dd-home-left"><article class="dd-hero dd-motion-card"><div class="dd-hero-copy"><span class="dd-hero-kicker">TU SIGUIENTE PASO</span><h2>Explora opciones que conectan con lo que te interesa.</h2><p>Compara requisitos, duración y modalidad antes de decidir qué quieres revisar.</p><div class="dd-hero-tags">'+(interests.length?interests.map(function(x){return'<span>'+esc(x)+'</span>';}).join(''):'<span>Descubre nuevas opciones</span>')+'</div><button class="dd-primary-btn" type="button" data-dd-nav="opportunities">Explorar oportunidades →</button></div><div class="dd-hero-visual">'+youthIllustration()+'</div></article><article class="dd-card dd-opp-preview dd-motion-card">'+sectionHead('Oportunidades para explorar','Opciones verificadas relacionadas con tu perfil.','<button class="dd-link-btn" type="button" data-dd-nav="opportunities">Ver todas →</button>')+'<div class="dd-opps-3">'+opps.map(miniOpp).join('')+'</div></article></div><div class="dd-home-right"><article class="dd-card dd-quick dd-motion-card">'+sectionHead('Tu avance hoy','Solo información registrada en esta sesión.')+'<div class="dd-stat-grid">'+quick.map(function(x){return'<div class="dd-stat"><div class="dd-stat-icon">'+icon(x.icon)+'</div><strong '+(!x.percent&&/^\d+$/.test(x.value)?'data-count="'+esc(x.value)+'"':'')+'>'+(x.percent?'<span data-count="'+esc(x.value)+'">0</span>%':esc(x.value))+'</strong><span>'+esc(x.label)+'</span></div>';}).join('')+'</div></article><article class="dd-card dd-continue dd-motion-card">'+sectionHead('Continúa tu ruta','Retoma cuando quieras.','<button class="dd-link-btn" type="button" data-dd-nav="route">Ir a Mi Ruta →</button>')+'<div class="dd-continue-body"><div class="dd-thumb">'+icon('route')+'</div><div class="dd-course-meta"><h4>'+esc(m.routeSkillsStarted?'Fortalece habilidades':'Tu punto de partida ya está creado')+'</h4><p>'+esc(m.routeSkillsStarted?'Ya comenzaste la segunda etapa.':'El siguiente paso puede ser explorar habilidades y oportunidades.')+'</p></div>'+ring(m.routeProgress,'de tu ruta')+'</div></article></div></div>'].join('');}
  function routeStep  function routeStep(s){return'<div class="dd-route-step '+(s.status==='done'?'is-complete':s.status==='current'?'is-current':'')+'"><span class="dd-route-num">'+s.n+'</span><div><h4>'+esc(s.title)+'</h4><p>'+esc(s.desc)+'</p></div><span class="dd-status-pill '+(s.status==='done'?'done':s.status==='current'?'current':'')+'">'+esc(s.label)+'</span></div>';}
  function bigRing(p){return'<div class="dd-big-ring" data-progress="'+Number(p||0)+'" style="--p:0"><strong data-ring-value>0%</strong></div>';}
  function signals(values){var rows=(values||[]).slice(0,5);if(!rows.length)return'<div class="dd-signal">Aún no registrado</div>';return rows.map(function(v){return'<div class="dd-signal">'+esc(v)+'</div>';}).join('');}
  function renderRoute(){var m=getModel(),p=document.querySelector('[data-dd-page="route"]');if(!p)return;var route=buildRouteModel(m),steps=route.steps,current=steps.find(function(s){return s.status==='current';})||steps[1]||steps[0];p.innerHTML=[pageHead('MI RUTA','Tu camino, paso a paso','Visualiza lo que ya hiciste y decide cuándo avanzar.','<span class="dd-profile-ready">'+m.routeProgress+'% de la ruta iniciada</span>'),'<div class="dd-route-v3"><article class="dd-card dd-route-map-card dd-motion-card"><div class="dd-route-map-copy"><span class="dd-eyebrow">MAPA DE RUTA</span><h2>Construye tu camino a tu ritmo.</h2><p>Las etapas cambian con acciones reales dentro de DESPEGA.</p></div>'+routeMap(route)+'</article><div class="dd-route-lower"><article class="dd-card dd-current-step dd-motion-card"><span class="dd-current-badge">AHORA</span><h2>'+esc(current.title)+'</h2><p>'+esc(current.desc)+'</p><div class="dd-current-actions"><button class="dd-primary-btn" type="button" id="ddStartSkills">'+esc(state.routeSkillsStarted?'Continuar →':'Comenzar →')+'</button><button class="dd-outline-btn" type="button" data-dd-nav="opportunities">Ver opciones</button></div></article><article class="dd-card dd-route-progress dd-motion-card">'+sectionHead('Tu avance','Etapas completadas y pendientes.')+'<div class="dd-progress-row">'+bigRing(m.routeProgress)+'<div class="dd-progress-list">'+steps.map(function(s){return'<div class="dd-progress-item"><span><i class="dd-progress-dot '+(s.status==='done'?'done':s.status==='current'?'current':'')+'"></i>'+esc(s.n+'. '+s.title)+'</span><strong>'+esc(s.status==='done'?'✓':s.status==='current'?'•':'—')+'</strong></div>';}).join('')+'</div></div></article></div><div class="dd-signal-grid"><article class="dd-card dd-signal-card dd-motion-card">'+sectionHead('Fortalezas identificadas','Basadas en tu conversación con Nova.')+'<div class="dd-signal-list">'+signals(m.skills)+'</div></article><article class="dd-card dd-signal-card dd-motion-card">'+sectionHead('Barreras actuales','Solo lo que registraste.')+'<div class="dd-signal-list">'+signals(m.barriers)+'</div></article></div></div>'].join('');var start=document.getElementById('ddStartSkills');if(start)start.addEventListener('click',function(){state.routeSkillsStarted=true;localStorage.setItem('despegaRouteSkillsStarted','true');toast('Etapa de habilidades marcada como en curso.');renderAll();});}
  function filteredCatalog  function filteredCatalog(){var q=state.search.trim().toLowerCase(),cat=state.category;return activeCatalog().filter(function(o){var catOk=cat==='all'||o.type===cat,hay=(o.title+' '+o.provider+' '+o.description+' '+o.tags.join(' ')).toLowerCase();return catOk&&(!q||hay.indexOf(q)>=0);});}
  function opportunityCard(o){var saved=state.saved.indexOf(o.id)>=0,reasons=getModel&&matchReasons?matchReasons(o,getModel()):[];return'<article class="dd-card dd-opportunity dd-motion-card" data-opportunity-id="'+esc(o.id)+'"><div class="dd-opp-image">'+opportunityIllustration(o.type)+'<span class="dd-type">'+esc(titleCase(o.type))+'</span><button class="dd-heart '+(saved?'is-saved':'')+'" type="button" data-dd-save="'+esc(o.id)+'" aria-label="'+esc(saved?'Quitar de guardadas':'Guardar oportunidad')+'">'+(saved?'♥':'♡')+'</button></div><div class="dd-opp-body"><h3>'+esc(o.title)+'</h3><div class="dd-provider">'+esc(o.provider)+'</div><div class="dd-opp-desc">'+esc(o.description)+'</div><div class="dd-opp-info"><span>'+icon('home')+esc(o.modality)+'</span><span>'+esc(o.duration)+'</span><span>'+esc(o.cost)+'</span></div><button class="dd-why-toggle" type="button" data-dd-why="'+esc(o.id)+'">¿Por qué aparece?</button><div class="dd-why-drawer" data-dd-why-panel="'+esc(o.id)+'" hidden><strong>Aparece porque:</strong>'+(reasons.length?'<ul>'+reasons.map(function(r){return'<li>'+esc(r)+'</li>';}).join('')+'</ul>':'<p>Está disponible en el catálogo verificado de DESPEGA.</p>')+'</div><div class="dd-opp-actions"><button class="dd-outline-btn" type="button" data-dd-save="'+esc(o.id)+'">'+(saved?'Guardada ✓':'Guardar')+'</button><button class="dd-primary-btn" type="button" data-dd-detail="'+esc(o.id)+'">Ver detalles →</button></div></div></article>';}
  function renderOpportunities(){var p=document.querySelector('[data-dd-page="opportunities"]');if(!p)return;var rows=filteredCatalog();p.innerHTML=[pageHead('OPORTUNIDADES','Explora opciones verificadas','Filtra, compara y revisa por qué aparece cada opción. Tú decides qué explorar.',''),'<article class="dd-card dd-toolbar dd-motion-card"><div class="dd-search-row"><input class="dd-search" id="ddSearch" type="search" value="'+esc(state.search)+'" placeholder="Buscar por título, institución o tema..."><button class="dd-filter-btn" type="button">Filtros</button></div><div class="dd-category-row">'+[['all','Todo'],['curso','Cursos'],['beca','Becas'],['empleo','Empleo'],['evento','Eventos'],['voluntariado','Voluntariado']].map(function(x){return'<button class="dd-chip-btn '+(state.category===x[0]?'is-active':'')+'" type="button" data-dd-category="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</div><div class="dd-filter-row"><select class="dd-select" aria-label="Modalidad"><option>Modalidad</option><option>En línea</option><option>Presencial</option><option>Mixta</option></select><select class="dd-select" aria-label="Nivel educativo"><option>Nivel educativo</option><option>Secundaria</option><option>Abierto</option></select><select class="dd-select" aria-label="Costo"><option>Costo</option><option>Gratuito</option><option>Por revisar</option></select></div></article><div class="dd-opportunities-head"><p>'+rows.length+' opciones verificadas</p><span>Fuentes oficiales revisadas por DESPEGA</span></div><div class="dd-opportunity-grid">'+(rows.length?rows.map(opportunityCard).join(''):'<div class="dd-card dd-empty">No encontramos opciones con esos filtros.</div>')+'</div>'].join('');var search=document.getElementById('ddSearch');if(search)search.addEventListener('input',function(){state.search=search.value;renderOpportunities();initDashboardMotion();});Array.prototype.forEach.call(p.querySelectorAll('[data-dd-category]'),function(btn){btn.addEventListener('click',function(){state.category=btn.getAttribute('data-dd-category')||'all';renderOpportunities();initDashboardMotion();});});Array.prototype.forEach.call(p.querySelectorAll('[data-dd-why]'),function(btn){btn.addEventListener('click',function(){var id=btn.getAttribute('data-dd-why'),panel=p.querySelector('[data-dd-why-panel="'+id+'"]');if(!panel)return;var willOpen=panel.hidden;Array.prototype.forEach.call(p.querySelectorAll('.dd-why-drawer'),function(x){x.hidden=true;});panel.hidden=!willOpen;btn.setAttribute('aria-expanded',String(willOpen));});});bindOpportunityActions(p);}
  function bindOpportunityActions  function bindOpportunityActions(scope){Array.prototype.forEach.call(scope.querySelectorAll('[data-dd-save]'),function(btn){btn.addEventListener('click',function(e){e.stopPropagation();toggleSaved(btn.getAttribute('data-dd-save'));});});Array.prototype.forEach.call(scope.querySelectorAll('[data-dd-detail]'),function(btn){btn.addEventListener('click',function(){openDetails(btn.getAttribute('data-dd-detail'));});});}
  function toggleSaved(id){if(!id)return;var i=state.saved.indexOf(id);if(i>=0){state.saved.splice(i,1);toast('Oportunidad retirada de guardadas.');}else{state.saved.push(id);toast('Oportunidad guardada para revisarla después.');}saveJSON('despegaSavedOpportunities',state.saved);renderAll();}
  function openDetails(id){var o=catalog.find(function(x){return x.id===id;});if(!o||!isVerifiedOpportunity(o))return;if(state.viewed.indexOf(id)<0){state.viewed.push(id);saveJSON('despegaViewedOpportunities',state.viewed);}var modal=document.getElementById('ddModal'),card=document.getElementById('ddModalCard');if(!modal||!card)return;var reqs=Array.isArray(o.requirements)&&o.requirements.length?'<div class="dd-modal-requirements"><strong>Requisitos registrados</strong><ul>'+o.requirements.map(function(r){return'<li>'+esc(r)+'</li>';}).join('')+'</ul></div>':'';var verified='<span class="dd-verified-source">✓ Fuente oficial verificada el '+esc(o.verification.verified_at)+'</span>';card.innerHTML='<button class="dd-modal-close" type="button" aria-label="Cerrar">×</button><span class="dd-type">'+esc(titleCase(o.type))+'</span><h2>'+esc(o.title)+'</h2>'+verified+'<p>'+esc(o.description)+'</p><div class="dd-modal-facts"><div class="dd-modal-fact"><strong>Fuente</strong>'+esc(o.provider)+'</div><div class="dd-modal-fact"><strong>Modalidad</strong>'+esc(o.modality)+'</div><div class="dd-modal-fact"><strong>Duración</strong>'+esc(o.duration)+'</div><div class="dd-modal-fact"><strong>Costo</strong>'+esc(o.cost)+'</div></div>'+reqs+'<p>Antes de decidir, revisa la información vigente en el sitio oficial.</p><div class="dd-modal-actions"><button class="dd-outline-btn" type="button" data-dd-modal-save="'+esc(o.id)+'">'+(state.saved.indexOf(o.id)>=0?'Guardada ✓':'Guardar oportunidad')+'</button><button class="dd-primary-btn" type="button" data-dd-official="'+esc(o.id)+'">Abrir sitio oficial ↗</button></div>';modal.classList.add('is-open');card.querySelector('.dd-modal-close').addEventListener('click',closeModal);card.querySelector('[data-dd-modal-save]').addEventListener('click',function(){toggleSaved(o.id);closeModal();});card.querySelector('[data-dd-official]').addEventListener('click',function(){var url=getVerifiedUrl(o.id);if(url)window.open(url,'_blank','noopener,noreferrer');});renderAll();}
  function closeModal(){var m=document.getElementById('ddModal');if(m)m.classList.remove('is-open');}
  function goalRow(done,label){return'<div class="dd-goal '+(done?'is-done':'')+'"><span class="dd-goal-check">'+(done?'✓':'')+'</span><span>'+esc(label)+'</span></div>';}
  function achievementCards(m){var rows=[];if(m.completedOnboarding)rows.push(['Punto de partida','Completaste tu onboarding y perfil.']);if(m.viewedCount)rows.push(['Explorador/a','Revisaste '+m.viewedCount+' oportunidad(es).']);if(m.savedCount)rows.push(['Guardadas','Conservaste '+m.savedCount+' opción(es) para comparar.']);if(!rows.length)rows.push(['Primer hito','Tus logros reales aparecerán aquí.']);return rows.map(function(x){return'<div class="dd-achievement"><strong>'+esc(x[0])+'</strong><span>'+esc(x[1])+'</span></div>';}).join('');}
  function renderProgress(){var m=getModel(),p=document.querySelector('[data-dd-page="progress"]');if(!p)return;var nextTitle=m.viewedCount?(m.savedCount?'Inicia la etapa de habilidades':'Guarda una opción para compararla'):'Explora tu primera oportunidad',nextView=m.viewedCount?'route':'opportunities';p.innerHTML=[pageHead('TU PROGRESO','Mira cuánto has avanzado','Cada hito aparece cuando realizas una acción real dentro de DESPEGA.',''),'<div class="dd-progress-v3"><article class="dd-card dd-progress-focus dd-motion-card"><div>'+bigRing(m.routeProgress)+'</div><div><span class="dd-eyebrow">TU RUTA</span><h2><span data-count="'+m.routeProgress+'">0</span>% de tu ruta iniciada</h2><p>'+esc(m.completedOnboarding?'Ya construiste tu punto de partida. Los siguientes hitos aparecen cuando exploras y actúas.':'Completa tu onboarding para iniciar la ruta.')+'</p></div></article><article class="dd-card dd-next-goal dd-motion-card"><span class="dd-current-badge">SIGUIENTE HITO</span><h2>'+esc(nextTitle)+'</h2><p>Avanza cuando quieras; DESPEGA organiza la información para que compares antes de decidir.</p><button class="dd-primary-btn" type="button" data-dd-nav="'+esc(nextView)+'">Continuar →</button></article><article class="dd-card dd-timeline dd-motion-card">'+sectionHead('Tu camino hasta ahora','Acciones registradas en el prototipo.')+'<div class="dd-timeline-list">'+timelineRow(m.completedOnboarding,'Perfil creado','Onboarding y conversación inicial completados.')+timelineRow(m.usefulAnswers>0,m.usefulAnswers+' respuestas con Nova','Información útil registrada para tu ruta.')+timelineRow(m.viewedCount>0,'Exploraste una oportunidad',m.viewedCount?m.viewedCount+' opción(es) revisadas.':'Aún no has abierto una oportunidad.')+timelineRow(m.savedCount>0,'Guardaste una opción',m.savedCount?m.savedCount+' opción(es) guardadas.':'Puedes guardar una opción para compararla después.')+timelineRow(state.routeSkillsStarted,'Iniciaste habilidades','La segunda etapa de la ruta está en curso.')+'</div></article></div>'].join('');}
  function profileRow  function profileRow(symbol,label,value){return'<div class="dd-profile-row"><span class="dd-profile-icon">'+symbol+'</span><div><small>'+esc(label)+'</small><strong>'+esc(value)+'</strong></div></div>';}
  function renderProfile(){var m=getModel(),p=document.querySelector('[data-dd-page="profile"]');if(!p)return;var mainGoal=m.goals[0]||'Aún no registrado',pc=profileCompleteness(m);p.innerHTML=[pageHead('TU PERFIL','Así te estamos conociendo','Revisa tus datos y lo que Nova identificó con evidencia de tu conversación.','<span class="dd-profile-ready">'+(m.completedOnboarding?'Onboarding completado':'Onboarding pendiente')+'</span>'),'<div class="dd-profile-v3"><article class="dd-card dd-profile-summary dd-motion-card">'+sectionHead('Resumen personal',pc.missing?pc.missing+' dato(s) básico(s) por completar.':'Tus datos básicos están registrados.','<button class="dd-link-btn" type="button" id="ddEditProfile">Ver y editar →</button>')+'<div class="dd-profile-completeness"><strong>'+pc.percent+'%</strong><span>datos básicos</span></div>'+profileRow('⌂','Nivel educativo',m.education)+profileRow('◎','Meta principal',mainGoal)+profileRow('⌖','Ubicación',m.location||'Por completar')+profileRow('◫','Situación actual','Estudia: '+m.studying+' · Trabaja: '+m.working)+'</article><article class="dd-card dd-nova-insights dd-motion-card">'+sectionHead('Lo que Nova entendió','Habilidades y experiencia permanecen separadas.')+'<div class="dd-insights-grid"><div class="dd-insight interests"><h3>Intereses</h3><div class="dd-tags">'+tagRows(m.interests,6)+'</div></div><div class="dd-insight skills"><h3>Habilidades</h3><div class="dd-tags">'+tagRows(m.skills,6)+'</div></div><div class="dd-insight experience"><h3>Experiencia</h3><div class="dd-tags">'+tagRows(m.experience,6)+'</div></div><div class="dd-insight goals"><h3>Metas</h3><div class="dd-tags">'+tagRows(m.goals,6)+'</div></div><div class="dd-insight barriers"><h3>Barreras</h3><div class="dd-tags">'+tagRows(m.barriers,6)+'</div></div></div></article></div>'].join('');var edit=document.getElementById('ddEditProfile');if(edit)edit.addEventListener('click',function(){toast('La edición del perfil se habilitará sobre los datos existentes sin borrar tu conversación.');});}
  function renderAll  function renderAll(){var pages=['home','route','opportunities','progress','profile'];pages.forEach(function(v){var node=document.querySelector('[data-dd-page="'+v+'"]');if(node)node.classList.toggle('is-active',state.view===v);});renderHome();renderRoute();renderOpportunities();renderProgress();renderProfile();Array.prototype.forEach.call(root.querySelectorAll('[data-dd-nav]'),function(btn){if(btn.getAttribute('data-dd-nav')===state.view)btn.setAttribute('aria-current','page');else btn.removeAttribute('aria-current');});var message=document.getElementById('ddNovaMessage'),m=getModel();if(message)message.textContent='Hola '+m.firstName+'. Puedo ayudarte a revisar lo que registraste, entender tu ruta o abrir el catálogo de opciones. Tú decides qué explorar.';initDashboardMotion();}
  function setView(view){if(['home','route','opportunities','progress','profile'].indexOf(view)<0)return;state.view=view;localStorage.setItem('despegaDashboardView',view);renderAll();var main=root.querySelector('.dd-main');if(main)main.scrollTo({top:0,behavior:'smooth'});}
  function bindShell(){root.addEventListener('click',function(event){var nav=event.target.closest('[data-dd-nav]');if(nav){setView(nav.getAttribute('data-dd-nav'));return;}var novaGo=event.target.closest('[data-dd-nova-go]');if(novaGo){setView(novaGo.getAttribute('data-dd-nova-go'));toggleNova(false);return;}});var launcher=document.getElementById('ddNovaLauncher'),close=document.querySelector('.dd-nova-close');if(launcher)launcher.addEventListener('click',function(){toggleNova();});if(close)close.addEventListener('click',function(){toggleNova(false);});var modal=document.getElementById('ddModal');if(modal)modal.addEventListener('click',function(e){if(e.target===modal)closeModal();});}
  function toggleNova(force){state.novaOpen=typeof force==='boolean'?force:!state.novaOpen;var panel=document.getElementById('ddNovaPanel'),launcher=document.getElementById('ddNovaLauncher');if(panel)panel.classList.toggle('is-open',state.novaOpen);if(launcher){launcher.classList.toggle('is-open',state.novaOpen);launcher.setAttribute('aria-expanded',String(state.novaOpen));}}
  var toastTimer=null;function toast(message){var node=document.getElementById('ddToast');if(!node)return;node.textContent=message;node.classList.add('is-show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){node.classList.remove('is-show');},2300);}
  function syncDashboardMode(){var active=!dashboardView.hidden;document.body.classList.toggle('dashboard-mode',active);if(active){if(!root.firstChild)shell();else renderAll();}}
  new MutationObserver(syncDashboardMode).observe(dashboardView,{attributes:true,attributeFilter:['hidden']});
  document.addEventListener('keydown',function(e){if(e.key==='Escape'){toggleNova(false);closeModal();}});
  window.DESPEGA_DASHBOARD_API=Object.freeze({
    navigate:setView,
    getCurrentView:function(){return state.view;},
    getCatalog:function(){return activeCatalog().map(function(item){return JSON.parse(JSON.stringify(item));});},
    getOpportunity:function(id){var item=catalog.find(function(row){return row.id===id&&isVerifiedOpportunity(row);});return item?JSON.parse(JSON.stringify(item)):null;},
    getVerifiedUrl:getVerifiedUrl,
    getRoute:function(){return JSON.parse(JSON.stringify(buildRouteModel(getModel())));},
    getMatchReasons:function(id){var item=catalog.find(function(row){return row.id===id&&isVerifiedOpportunity(row);});return item?matchReasons(item,getModel()):[];},
    openOpportunity:function(id){openDetails(id);},
    saveOpportunity:function(id){var item=catalog.find(function(row){return row.id===id&&isVerifiedOpportunity(row);});if(item)toggleSaved(id);},
    getSavedIds:function(){return state.saved.slice();},
    getViewedIds:function(){return state.viewed.slice();}
  });
  shell();syncDashboardMode();
})();
