create table if not exists public.nova_chat_sessions (
  id uuid primary key,
  onboarding_session_id text not null,
  summary text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists nova_chat_sessions_onboarding_idx
  on public.nova_chat_sessions (onboarding_session_id);

create table if not exists public.nova_chat_messages (
  id uuid primary key default gen_random_uuid(),
  chat_session_id uuid not null references public.nova_chat_sessions(id) on delete cascade,
  message_id text not null,
  role text not null check (role in ('user','assistant')),
  content text not null,
  current_view text not null default 'home',
  reply_to_message_id text,
  model text not null default '',
  latency_ms integer not null default 0,
  error_code text not null default '',
  created_at timestamptz not null default now(),
  unique (chat_session_id, message_id, role)
);

create index if not exists nova_chat_messages_session_created_idx
  on public.nova_chat_messages (chat_session_id, created_at);
create index if not exists nova_chat_messages_reply_idx
  on public.nova_chat_messages (chat_session_id, reply_to_message_id);

create table if not exists public.nova_chat_diagnostics (
  id bigint generated by default as identity primary key,
  chat_session_id uuid not null references public.nova_chat_sessions(id) on delete cascade,
  message_id text not null,
  current_view text not null default 'home',
  input_length integer not null default 0,
  output_length integer not null default 0,
  model text not null default '',
  latency_ms integer not null default 0,
  status text not null default 'ok',
  error_code text not null default '',
  created_at timestamptz not null default now(),
  unique (chat_session_id, message_id)
);

alter table public.nova_chat_sessions enable row level security;
alter table public.nova_chat_messages enable row level security;
alter table public.nova_chat_diagnostics enable row level security;

revoke all on public.nova_chat_sessions from anon, authenticated;
revoke all on public.nova_chat_messages from anon, authenticated;
revoke all on public.nova_chat_diagnostics from anon, authenticated;
